
#ifndef __CHANNEL_H__
#define __CHANNEL_H__

#define NB_PHYSICAL_CHANNEL 8
#define NB_LOGIC_CHANNEL NB_PHYSICAL_CHANNEL

#define NB_PARAMETER_CHANNELS_FOR_EACH_LOGICAL_CHANNEL 12
#define NB_STEP_PARAMETER_CHANNELS (NB_LOGIC_CHANNEL* NB_PARAMETER_CHANNELS_FOR_EACH_LOGICAL_CHANNEL)

#define LOGICAL_CHANNEL_ID_DIFF 1

#endif // __CHANNEL_H__
