/**
* @file     dac_ti8568.h
* @brief    dac_ti8568.h
* @author   Joe.Zhong <wenxing.cn@gmail.com>
* @date     13/11/2018
*/

#ifndef __DAC_TI8568_H__
#define __DAC_TI8568_H__

#define DAC1_DEVICE_SIGNATURE "U2"
#define DAC2_DEVICE_SIGNATURE "U3"

#define DAC1_VOUTA_TERMINAL_SIGNATURE "VU1"
#define DAC1_VOUTB_TERMINAL_SIGNATURE "VI1"
#define DAC1_VOUTC_TERMINAL_SIGNATURE "VU2"
#define DAC1_VOUTD_TERMINAL_SIGNATURE "VI2"
#define DAC1_VOUTE_TERMINAL_SIGNATURE "VU3"
#define DAC1_VOUTF_TERMINAL_SIGNATURE "VI3"
#define DAC1_VOUTG_TERMINAL_SIGNATURE "VU4"
#define DAC1_VOUTH_TERMINAL_SIGNATURE "VI4"

#define DAC1_VOUTA_ADDRESS_BITS 0
#define DAC1_VOUTB_ADDRESS_BITS 1
#define DAC1_VOUTC_ADDRESS_BITS 2
#define DAC1_VOUTD_ADDRESS_BITS 3
#define DAC1_VOUTE_ADDRESS_BITS 4
#define DAC1_VOUTF_ADDRESS_BITS 5
#define DAC1_VOUTG_ADDRESS_BITS 6
#define DAC1_VOUTH_ADDRESS_BITS 7

#define DAC2_VOUTA_TERMINAL_SIGNATURE "VU5"
#define DAC2_VOUTB_TERMINAL_SIGNATURE "VI5"
#define DAC2_VOUTC_TERMINAL_SIGNATURE "VU6"
#define DAC2_VOUTD_TERMINAL_SIGNATURE "VI6"
#define DAC2_VOUTE_TERMINAL_SIGNATURE "VU7"
#define DAC2_VOUTF_TERMINAL_SIGNATURE "VI7"
#define DAC2_VOUTG_TERMINAL_SIGNATURE "VU8"
#define DAC2_VOUTH_TERMINAL_SIGNATURE "VI8"

#define DAC2_VOUTA_ADDRESS_BITS 0
#define DAC2_VOUTB_ADDRESS_BITS 1
#define DAC2_VOUTC_ADDRESS_BITS 2
#define DAC2_VOUTD_ADDRESS_BITS 3
#define DAC2_VOUTE_ADDRESS_BITS 4
#define DAC2_VOUTF_ADDRESS_BITS 5
#define DAC2_VOUTG_ADDRESS_BITS 6
#define DAC2_VOUTH_ADDRESS_BITS 7

#define DAC1_EXTERNAL_VREF  5.0
#define DAC2_EXTERNAL_VREF  5.0    

int dac_ti8568_init(register_dac_parameters *);
int dac_ti8568_ioctl(dac_ioctl_parameters *);
int dac_ti8568_deinit(unregister_dac_parameters *);

#endif // __DAC_TI8568_H__
