
#ifndef __ERROR_MSG_H__
#define __ERROR_MSG_H__

/* For ERROR_PHYSICAL_CHANNEL_LOST_CONTROL */
#define ERROR_MSG_PHYSICAL_CURRENT_EXCEEDED 1
#define ERROR_MSG_PHYSICAL_VOLTAGE_EXCEEDED 2



#endif // __ERROR_MSG_H__