/**
* @file     error_no.h
* @brief    error_no.h
* @author   Joe.Zhong <wenxing.cn@gmail.com>
* @date     12/12/2018
*/

#ifndef __ERROR_NO_H__
#define __ERROR_NO_H__

//positive group
#define JUMP_CONDICTION_TIME         1
#define JUMP_CONDICTION_VOLTAGE      2
#define JUMP_CONDICTION_CURRENT      3
#define JUMP_CONDICTION_CYCLE        4
#define JUMP_CONDICTION_GOTO         5
#define JUMP_CONDICTION_CAPACITY     6

#define ERROR_FOR_DEBUG_PURPOSE -1

// negative group
#define ERROR_PHYSICAL_CHANNEL_BUSY   -100

#define ERROR_BINDING_REGISTER_ZERO  -101

#define ERROR_STEP_POINTER_NONZERO -102

#define ERROR_UNKNOWN_STEP_TYPE -103

#define ERROR_STEP_QUANTITY_ZERO -104

#define ERROR_STEP_QUANTITY_EXCESS -105

#define ERROR_PHYSICAL_CHANNEL_LOST_CONTROL -106

#define ERROR_SOURCE_CURRENT_CAPACITY_ZERO -107

#define ERROR_JUMP_CONDICTION_ENABLE_ZERO -108
#define ERROR_JUMP_CONDICTION_TIME_ZERO -109
#define ERROR_JUMP_CONDICTION_VOLTAGE_ZERO -110
#define ERROR_JUMP_CONDICTION_CURRENT_ZERO -111

#define ERROR_JUMP_CONDICTION_TIMEOUT_NOT_SET -112
#define ERROR_JUMP_CONDICTION_VOLTAGE_NOT_SET -113
#define ERROR_JUMP_CONDICTION_CURRENT_NOT_SET -114

#define ERROR_COMMON_NODE_VOLTAGE_TOLERANCE_EXCEEDED -115 
#define ERROR_UNKNOWN_LOGICAL_CHANNEL_ID    -116
#define ERROR_INCORRECT_STEP_POINTER        -117
#define ERROR_INTERNEL_ERRORS           -118

#define ERROR_FIRST_STEP_IS_CYCLE    -119
#define ERROR_FIRST_STEP_IS_GOTO     -120

#define ERROR_UNKNOWN_GOTO_BEHAVIOR  -121

#define ERROR_CONSTANT_CURRENT_LIMIT_EXCEEDED -122
#define ERROR_CCC_CURRENT_ZERO              -123
#define ERROR_CCD_CURRENT_ZERO              -124
#define ERROR_CCCCVC_CURRENT_ZERO              -125
#define ERROR_CCDCVD_CURRENT_ZERO              -125
#define ERROR_CCD_CURRENT_POSITIVE              -126
#define ERROR_CCC_CURRENT_NEGATIVE              -127
#define ERROR_CCCCVC_CURRENT_NEGATIVE           -128
#define ERROR_CCDCVD_CURRENT_POSITIVE           -129
#define ERROR_CPC_POWER_ZERO        -130
#define ERROR_CRD_RESISTANCE_ZERO   -131
#define ERROR_CPD_POWER_ZERO        -132
#define ERROR_POWER_LIMIT_EXCEEDED  -133
#define ERROR_UNKNOWN_PHYSICAL_CHANNEL_CURRENT_SOURCE_LEVEL -134

#define ERROR_UNKNOWN_CALIBRATION_STEP_TYPE         -135
#define ERROR_CCC_CALIBRATION_VOLTAGE_ZERO          -136
#define ERROR_CCC_CALIBRATION_CURRENT_ZERO          -137
#define ERROR_CCD_CALIBRATION_CURRENT_ZERO          -138
#define ERROR_CCD_CALIBRATION_VOLTAGE_ZERO          -139
#define ERROR_CVDA_CALIBRATION_CURRENT_ZERO          -140
#define ERROR_CVDA_CALIBRATION_VOLTAGE_ZERO          -141
#define ERROR_CVAD_CALIBRATION_CURRENT_ZERO          -142
#define ERROR_CVAD_CALIBRATION_VOLTAGE_ZERO          -143

#define ERROR_CALIBRATION_CURRENT_LIMIT_EXCEEDED    -144

#define ERROR_BINDING_REGISTER_NONZERO          -145
#define ERROR_STEP_QUANTITY_MORE_THAN_ONE       -146
#define ERROR_NO_SUCH_FILE_OR_DIRECTORY         -147
#define ERROR_READ_RECOVERY_FILE_FAIL          -148

#define ERROR_READ_RECOVERY_FILE_FAIL          -148

#define ERROR_ACCUMULATED_LOGIC_CAPACITY_NONZERO    -149
#define ERROR_LAST_ACCUMULATED_LOGIC_CAPACITY_SAMPLING_TIME_NONZERO     -150

#endif // __ERROR_NO_H__

