/**
* @file     register_values.h
* @brief    register_values.h
* @author   Joe.Zhong <wenxing.cn@gmail.com>
* @date     12/12/2018
*/

#ifndef __REGISTER_VALUES_H__
#define __REGISTER_VALUES_H__

/**/
#define MAX_STEP_QUANTITY 7860

// Formation testing
#define FORMATION_STEP_TYPE_CCC       1  /*Constant Current Charging */       /* Condiction: Time, Voltage, Capacity, Energy, negative delta V*/
#define FORMATION_STEP_TYPE_CCD       2  /*Constant Current Discharging */    /* Condiction: Time, Voltage, Capacity, Energy */
#define FORMATION_STEP_TYPE_CCCCVC    3  /*Constant Current Charging & Constant Voltage Charging */       /* Time, Capacity, Energy, Cut-off current */
#define FORMATION_STEP_TYPE_CCDCVD    4  /*Constant Voltage Discharging */    /* Time, Capacity, Energy, Cut-off current */
#define FORMATION_STEP_TYPE_CPC    5  /*Constant Power Charging */         /* Time, Voltage, Current, Capacity, Energy */
#define FORMATION_STEP_TYPE_CPD    6  /*Constant Power Discharging */      /* Time, Voltage, Current, Capacity, Energy */
#define FORMATION_STEP_TYPE_GOTO   7  /*If .... goto ....*/                /* Voltage, Current, Time, Capacity, Energy, Temperature */ /*Operators: >, >=, <=, <, = */
#define FORMATION_STEP_TYPE_REST   8  /* Rest */                            /* Time */
#define FORMATION_STEP_TYPE_CRD    9  /* Constant Resistance Discharging */  /* Time, Voltage, Current, Capacity, Energy */
#define FORMATION_STEP_TYPE_CYCLE  10 /* Cycle from step x to the step above for n times */ /*Cycle starting step ID, cycle number */   /* Jump Condiction: Cycle number */

#define CALIBRATION_STEP_TYPE_CCC   11
#define CALIBRATION_STEP_TYPE_CCD   12
#define CALIBRATION_STEP_TYPE_CVAD  13
#define CALIBRATION_STEP_TYPE_CVDA  14

#define STEP_JUMP_CONDICTION_TIMEOUT        0x0001
#define STEP_JUMP_CONDICTION_VOLTAGE        0x0002
#define STEP_JUMP_CONDICTION_CAPACITY       0x0004
#define STEP_JUMP_CONDICTION_ENERGY         0x0008
#define STEP_JUMP_CONDICTION_CURRENT        0x0010
#define STEP_JUMP_CONDICTION_TEMPERATURE    0x0020

#define STEP_INFO_COMMON_STATUS_NORMAL                              0
#define STEP_INFO_COMMON_STATUS_CCC_VOLTAGE_UPPER_LIMIT_REACHED     1
#define STEP_INFO_COMMON_STATUS_CCD_VOLTAGE_LOWER_LIMIT_REACHED     2
#define STEP_INFO_COMMON_STATUS_CHANNEL_DISABLED                    3
#define STEP_INFO_COMMON_STATUS_CCXCVX_VOLTAGE_LIMIT_REACHED        4
#define STEP_INFO_COMMON_STATUS_CCXCVX_CURRENT_LOWER_LIMIT_REACHED  5

#define PHYSICAL_CHANNEL_CURRENT_SOURCE_LEVEL_1    1
#define PHYSICAL_CHANNEL_CURRENT_SOURCE_LEVEL_2    2
#define PHYSICAL_CHANNEL_CURRENT_SOURCE_LEVEL_3    3


/* ASCII List
    G   0x47
    E   0x45
    L   0X4C
    T   0x54
*/
#define GOTO_OPERATOR_GT     0x4754   /* >  */
#define GOTO_OPERATOR_GE     0x4745   /* >= */
#define GOTO_OPERATOR_LT     0x4C54   /* <  */
#define GOTO_OPERATOR_LE     0x4C45   /* <= */

#define GOTO_BEHAVIOR_JUMP      0x0001
#define GOTO_BEHAVIOR_PAUSE     0x0002
#define GOTO_BEHAVIOR_FINISH    0x0004

#define DEFAULT_VI_SETTING_IN_MV_UNIT           2500
#define DEFAULT_VU_SETTING_IN_MV_UNIT           1000
#define DEFAULT_KZ_H_SETTING            0
#define DEFAULT_KZ_M_SETTING            0
#define DEFAULT_KZ_L_SETTING            1
#define DEFAULT_JC_SETTING              0
#define DEFAULT_CF_SETTING              0
#define DEFAULT_CK_SETTING              1
#define DEFAULT_CLED_SETTING            1
#define DEFAULT_FLED_SETTING            1
#define DEFAULT_CURRENT_SOURCE_LEVEL_SETTING    PHYSICAL_CHANNEL_CURRENT_SOURCE_LEVEL_1

#define DEFAULT_LAST_VI_SETTING         0xFFFF
#define DEFAULT_LAST_VU_SETTING         0xFFFF
#define DEFAULT_LAST_KZ_H_SETTING       0xFFFF
#define DEFAULT_LAST_KZ_M_SETTING       0xFFFF
#define DEFAULT_LAST_KZ_L_SETTING       0xFFFF
#define DEFAULT_LAST_JC_SETTING         0xFFFF
#define DEFAULT_LAST_CF_SETTING         0xFFFF
#define DEFAULT_LAST_CK_SETTING         0xFFFF
#define DEFAULT_LAST_CLED_SETTING       0xFFFF
#define DEFAULT_LAST_FLED_SETTING       0xFFFF
#define DEFAULT_LAST_CURRENT_SETTING    0
#define DEFAULT_LAST_VOLTAGE_SETTING    0
#define DEFAULT_LAST_CURRENT_SOURCE_LEVEL_SETTING   0

#define DEFAULT_READY_SETTING   0
#define DEFAULT_SOURCE_CURRENT_CAPACITY_LEVEL1_SETTING_IN_MA_UNIT  2
#define DEFAULT_SOURCE_CURRENT_CAPACITY_LEVEL2_SETTING_IN_MA_UNIT  5
#define DEFAULT_SOURCE_CURRENT_CAPACITY_LEVEL3_SETTING_IN_MA_UNIT  20

#define DEFAULT_PHYSICAL_CHANNEL_VU_IN_MV_UNIT  0
#define DEFAULT_PHYSICAL_CHANNEL_BV_IN_MV_UNIT  0

#define DEFAULT_PHYSICAL_CHANNEL_BV_K_IN_00001_UNIT               10000
#define DEFAULT_PHYSICAL_CHANNEL_VU_K_IN_00001_UNIT               10000

#define DEFAULT_PHYSICAL_CHANNEL_C_VI_K_FOR_L1_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_C_VI_K_FOR_L2_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_C_VI_K_FOR_L3_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_C_VI_B_FOR_L1_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_C_VI_B_FOR_L2_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_C_VI_B_FOR_L3_IN_01UA_UNIT      0

#define DEFAULT_PHYSICAL_CHANNEL_D_VI_K_FOR_L1_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_D_VI_K_FOR_L2_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_D_VI_K_FOR_L3_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_D_VI_B_FOR_L1_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_D_VI_B_FOR_L2_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_D_VI_B_FOR_L3_IN_01UA_UNIT      0

#define DEFAULT_PHYSICAL_CHANNEL_C_CV_K_FOR_L1_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_C_CV_K_FOR_L2_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_C_CV_K_FOR_L3_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_C_CV_B_FOR_L1_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_C_CV_B_FOR_L2_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_C_CV_B_FOR_L3_IN_01UA_UNIT      0

#define DEFAULT_PHYSICAL_CHANNEL_D_CV_K_FOR_L1_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_D_CV_K_FOR_L2_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_D_CV_K_FOR_L3_IN_00001_UNIT      10000
#define DEFAULT_PHYSICAL_CHANNEL_D_CV_B_FOR_L1_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_D_CV_B_FOR_L2_IN_01UA_UNIT      0
#define DEFAULT_PHYSICAL_CHANNEL_D_CV_B_FOR_L3_IN_01UA_UNIT      0

#define DEFAULT_STEP_TURNAROUND_DELAY_SETTING_IN_MS             200
#define DEFAULT_CALC_ACCUMULATED_CAPACITY_TIME_INTERVAL_IN_MS   100
#define DEFAULT_STEP_INFO_COMMON_SAMPLING_INTERVAL_IN_MS        100


#define IDEL_READY_SETTING              0
#define IDEL_VI_SETTING              2500
#define IDEL_VU_SETTING              1000
#define IDEL_KZ_H_SETTING               0
#define IDEL_KZ_M_SETTING               0
#define IDEL_KZ_L_SETTING               1
#define IDEL_JC_SETTING                 0
#define IDEL_CF_SETTING                 1
#define IDEL_CK_SETTING                 1
#define IDEL_CLED_SETTING               0
#define IDEL_FLED_SETTING               0

// Logical Channel Register Group
#define LOGICAL_CHANNEL_1_ID 0
#define LOGICAL_CHANNEL_2_ID 1
#define LOGICAL_CHANNEL_3_ID 2
#define LOGICAL_CHANNEL_4_ID 3
#define LOGICAL_CHANNEL_5_ID 4
#define LOGICAL_CHANNEL_6_ID 5
#define LOGICAL_CHANNEL_7_ID 6
#define LOGICAL_CHANNEL_8_ID 7

#define PHYSICAL_CHANNEL_1_ID 0
#define PHYSICAL_CHANNEL_2_ID 1
#define PHYSICAL_CHANNEL_3_ID 2
#define PHYSICAL_CHANNEL_4_ID 3
#define PHYSICAL_CHANNEL_5_ID 4
#define PHYSICAL_CHANNEL_6_ID 5
#define PHYSICAL_CHANNEL_7_ID 6
#define PHYSICAL_CHANNEL_8_ID 7

// every logical channel has 12 sub slave channels for its step parameters
#define NB_CHANNELS_FOR_STEP_PARAMETERS 12

#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH1_MASK_BIT 0x01
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH2_MASK_BIT 0x02
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH3_MASK_BIT 0x04
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH4_MASK_BIT 0x08
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH5_MASK_BIT 0x10
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH6_MASK_BIT 0x20
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH7_MASK_BIT 0x40
#define LOGICAL_CHANNEL_BINDING_REGISTER_PHYCH8_MASK_BIT 0x80

/* Mode */
#define LOGICAL_CHANNEL_HOLDING_REGISTER_MODE_CONFIGURATION  1
#define LOGICAL_CHANNEL_HOLDING_REGISTER_MODE_FORMATION      2
#define LOGICAL_CHANNEL_HOLDING_REGISTER_MODE_DEBUG          3
#define LOGICAL_CHANNEL_HOLDING_REGISTER_MODE_CALIBRATION    4
#define LOGICAL_CHANNEL_HOLDING_REGISTER_MODE_VERIFICATION   5
#define LOGICAL_CHANNEL_HOLDING_REGISTER_MODE_RECOVERY       6

/* Status */
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_IDEL            0
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_RUNNING         1
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_PAUSING         2
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_STOPPING        3
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_EXCEPTION       4
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_FINISHED        5
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_GOTO            6
#define LOGICAL_CHANNEL_HOLDING_REGISTER_STATUS_TRANSFORMING    7

/* Action */
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_NONE        0
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_START       1
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_STOP        2
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_PAUSE       3
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_RESUME      4
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_RESET       5
#define LOGICAL_CHANNEL_HOLDING_REGISTER_ACTION_RECOVERY    6


// Physical Channel Register Group
#define PHYSICAL_CHANNEL_HOLDING_REGISTER_STATUS_IDEL            0
#define PHYSICAL_CHANNEL_HOLDING_REGISTER_STATUS_RUNNING         1


#define PHYSICAL_CHANNEL_HOLDING_REGISTER_BEHAVIOR_REST     0
#define PHYSICAL_CHANNEL_HOLDING_REGISTER_BEHAVIOR_CCC      1

#define JC_ENABLE       0
#define JC_DISABLE      1

#define CLED_ENABLE     0
#define CLED_DISABLE    1

#define FLED_ENABLE     0
#define FLED_DISABLE    1

#define CF_ENABLE       1
#define CF_DISABLE      0

#define LED_READY_ENABLE    0
#define LED_READY_DISABLE   1

#define LED_RUN_ENABLE      0
#define LED_RUN_DISABLE     1

#define LED_ERROR_ENABLE    0
#define LED_ERROR_DISABLE   1

#define AC_LOSS_OFF         0
#define AC_LOSS_ON          1

#endif // __REGISTER_VALUES_H__

