/*
* @file     ssd1306_oled_raspberry_pi.h
* @brief    ssd1306_oled_raspberry_pi.h
* @author   Jerry.Chen <mikuyear@sina.cn>
* @date     31/1/2019
*/

#ifndef __SSD1306_OLED_RASPBERRY_PI_H__
#define __SSD1306_OLED_RASPBERRY_PI_H__

#define SSD1306_OLED1_DEVICE_SIGNATURE    "SSD1306_OLED"



#define SSD1306_OLED_POINT_ENABLE                   1
#define SSD1306_OLED_POINT_DISABLE                  0
#define SSD1306_OLED_POINT_MAX_ROW_COUNT           64
#define SSD1306_OLED_POINT_MAX_COLUMN_COUNT       128

#define SSD1306_OLED_BYTE_MAX_ROW_IDX               7//byte = width * higy = 1 * 8 pixel
#define SSD1306_OLED_BYTE_MAX_COLUMN_IDX          127//byte = width * higy = 1 * 8 pixel

#define SSD1306_OLED_CHAR_MAX_ROW_IDX               3//char = width * high = 8 * 16 pixel
#define SSD1306_OLED_CHAR_MAX_COLUMN_IDX           15//char = width * high = 8 * 16 pixel

#define SSD1306_OLED_BYTE_ROW_TO_START_PAGE_UNIT_FACTOR         1
#define SSD1306_OLED_BYTE_START_PAGE_TO_END_PAGE_OFFSET         0
#define SSD1306_OLED_BYTE_COLUMN_TO_START_COLUMN_UNIT_FACTOR    1
#define SSD1306_OLED_BYTE_START_COLUMN_TO_END_COLUMN_OFFSET     0

#define SSD1306_OLED_CHAR_ROW_TO_START_PAGE_UNIT_FACTOR         2
#define SSD1306_OLED_CHAR_START_PAGE_TO_END_PAGE_OFFSET         1
#define SSD1306_OLED_CHAR_COLUMN_TO_START_COLUMN_UNIT_FACTOR    8
#define SSD1306_OLED_CHAR_START_COLUMN_TO_END_COLUMN_OFFSET     7



#define SSD1306_OLED_MAX_PAGE_IDX                   7
#define SSD1306_OLED_MAX_COLUMN_IDX               127

#define SSD1306_OLED_ROW_IN_PIXEL                  64
#define SSD1306_OLED_COLUMN_IN_PIXEL              128
#define SSD1306_OLED_PIXEL_IN_BYTE               1024

//DATA HEAD | controller byte

#define SSD1306_OLED1_DEVICE_SIGNATURE_SSD1306_OLED_I2C_SLAVE_ADDR      0x3C

#define SSD1306_OLED_CONTROL_BYTE_ONY_BYTE_CMD_HEAR                     0X80
#define SSD1306_OLED_CONTROL_BYTE_ONY_BYTE_DATA_HEAR                    0XC0
#define SSD1306_OLED_CONTROL_BYTE_CONTINUE_BYTE_CMD_HEAR                0X00
#define SSD1306_OLED_CONTROL_BYTE_CONTINUE_BYTE_DATA_HEAR               0X40

//CMD AND CMD SETTING | data byte
//FUNDAMENTAL COMMAND TABLE

    //CONTRAST_CONTRO
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTRAST_CONTROL_HEAD                                                                                 0x81
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTRAST_CONTROL_SETTING_BYTE1_CONTRAST_LEVEL                                                         0X7F //0-254 reset 127

    //ENTIRE_DISPLAY_ON
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_ENTIRE_DISPLAY_ON_FOLLOWS_RAM_HEAD                                                                   0XA4

#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_ENTIRE_DISPLAY_ON_IGNORES_RAM_HEAD                                                                   0XA5

    //NORMAL_DISPLAY/INVERSE_DISPLAY
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_NORMAL_DISPLAY_HEAD                                                                              0XA6

#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_INVERSE_DISPLAY_HEAD                                                                             0XA7

    //DISPLAY_ON/DISPLAY_OFF
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_DISPLAY_OFF_HEAD                                                                                 0XAE

#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_DISPLAY_ON_HEAD                                                                                  0XAF

//SCROLLING COMMAND TABLE

    //CONTINUOUS_HORIZONTAL_SCROLL_SETUP
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_HEAD                                       0x26
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE1_DUMMY_BYTE                   0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE2_START_PAGE_ADDRESS           0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE3_TIME_INTERVAL                0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE4_END_PAGE_ADDRESS             7
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE5_DUMMY_BYTE                   0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE6_DUMMY_BYTE                   0xFF

#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_HEAD                                        0x27
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE1_DUMMY_BYTE                    0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE2_START_PAGE_ADDRESS            0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE3_TIME_INTERVAL                 0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE4_END_PAGE_ADDRESS              7
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE5_DUMMY_BYTE                    0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE6_DUMMY_BYTE                    0xFF

    //CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_HEAD                                       0x29
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE1_DUMMY_BYTE                   0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE2_START_PAGE_ADDRESS           0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE3_TIME_INTERVAL                0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE4_END_PAGE_ADDRESS             7
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_RIGHT_HORIZONTAL_SCROLL_SETTING_BYTE5_VERTICAL_SCROLLING_OFFSET    0x00

#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_HEAD                                        0x29
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE1_DUMMY_BYTE                    0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE2_START_PAGE_ADDRESS            0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE3_TIME_INTERVAL                 0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE4_END_PAGE_ADDRESS              7
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CONTINUOUS_VERTICAL_AND_HORIZONTAL_SCROLL_SETUP_LEFT_HORIZONTAL_SCROLL_SETTING_BYTE5_VERTICAL_SCROLLING_OFFSET     0x00

    //DEACTIVATE_SCROLL
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_DEACTIVATE_SCROLL_HEAD            0x2E

    //ACTIVATE_SCROLL
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_ACTIVATE_SCROLL_HEAD              0x2F

    //SET_VERTICAL_SCROLL_AREA
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VERTICAL_SCROLL_AREA_HEAD      0xA3
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VERTICAL_SCROLL_AREA_SETTING_BYTE1_NO_ROWS_IN_TOP_FIXED_AREA                    0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VERTICAL_SCROLL_AREA_SETTING_BYTE2_ROWS_TO_BE_USED_FOR_VERTICAL_SCROLLING       64

//ADDRESSING SETTING COMMAND TABLE

    //SET_MEMORY_ADDRESSING_MODE
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_MEMORY_ADDRESSING_MODE_HEAD                                            0x20
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_MEMORY_ADDRESSING_MODE_SETTING_BYTE1_HORIZONTAL_ADDRESSING_MODE        0x00
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_MEMORY_ADDRESSING_MODE_SETTING_BYTE1_VERTICAL_ADDRESSING_MODE          0x01
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_MEMORY_ADDRESSING_MODE_SETTING_BYTE1_PAGE_ADDRESSING_MODE              0x02

    //SET_LOWER_COLUMN_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE | ONLY FOR PAGE ADDRESSING MODE
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_LOWER_COLUMN_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE_HEAD      0x00 //0x00 ~ 0x0F

    //SET_HIGHER_COLUMN_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE | ONLY FOR PAGE ADDRESSING MODE
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_HIGHER_COLUMN_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE_HEAD     0x10 //0x10 ~ 0x1F

    //SET_COLUMN_ADDRESS | ONLY ONLY FOR HORIZONTAL OR VERTICAL ADDRESSING MODE
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COLUMN_ADDRESS_HEAD                                            0x21
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COLUMN_ADDRESS_SETTING_BYTE1_COLUMN_START_ADDRESS                 0 // 0 ~ 127
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COLUMN_ADDRESS_SETTING_BYTE2_COLUMN_END_ADDRESS                 127 // 0 ~ 127

    //SET_PAGE_ADDRESS | ONLY FOR HORIZONTAL OR VERTICAL ADDRESSING MODE
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_HEAD                                              0x22
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_0PAGE_START_ADDRESS                    0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_1PAGE_START_ADDRESS                    1
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_2PAGE_START_ADDRESS                    2
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_3PAGE_START_ADDRESS                    3
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_4PAGE_START_ADDRESS                    4
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_5PAGE_START_ADDRESS                    5
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_6PAGE_START_ADDRESS                    6
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE1_7PAGE_START_ADDRESS                    7
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_0PAGE_END_ADDRESS                      0
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_1PAGE_END_ADDRESS                      1
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_2PAGE_END_ADDRESS                      2
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_3PAGE_END_ADDRESS                      3
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_4PAGE_END_ADDRESS                      4
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_5PAGE_END_ADDRESS                      5
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_6PAGE_END_ADDRESS                      6
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PAGE_ADDRESS_SETTING_BYTE2_7PAGE_END_ADDRESS                      7

    //SET_PAGE_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_PAGE_START_ADDRESS_FOR_PAGE_ADDRESSING_MODE_HEAD               0xB0 // B0 ~ B7

//Hardware Configuration

    //SET_DISPLAY_START_LINE
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_DISPLAY_START_LINE_HEAD                 0x40 //0b01XXXXXX 0~63

    //SET_SEGMENT_REMAP
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_SEGMENT_REMAP_COLUMN_0_SEG0_HEAD                 0xA0

#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_SEGMENT_REMAP_COLUMN_127_SEG0_HEAD               0xA1

    //SET_MULTIPLEX_RATIO
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_MULTIPLEX_RATIO_HEAD                              0xA8
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_MULTIPLEX_RATIO_SETTING_BYTE1_MUX_RATIO           63 // 16 ~ 63 reset 63

    //SET_COM_OUTPUT_SCAN_DIRECTION
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_COM_OUTPUT_SCAN_DIRECTION_COM0_TO_COMN_HEAD      0xC0

#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_SET_COM_OUTPUT_SCAN_DIRECTION_COMN_TO_COM0_HEAD      0xC8

    //SET_DISPLAY_OFFSET
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_DISPLAY_OFFSET_HEAD      0xD3
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_DISPLAY_OFFSET_SETTING_BYTE1_SHIFT_BY_COM         0 // 0 ~ 63 reset 0

    //SET_COM_PINS_HARDWARE_CONFIGURATION
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COM_PINS_HARDWARE_CONFIGURATION_HEAD                                                                 0xDA
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COM_PINS_HARDWARE_CONFIGURATION_SETTING_BYTE1_SEQUENTIAL_COM_AND_DISABLE_COM_LEFT_RIGHT_REMAP        0x02 //reset
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COM_PINS_HARDWARE_CONFIGURATION_SETTING_BYTE1_ALTERNATIVE_COM_AND_DISABLE_COM_LEFT_RIGHT_REMAP       0x12
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COM_PINS_HARDWARE_CONFIGURATION_SETTING_BYTE1_SEQUENTIAL_COM_AND_ENABLE_COM_LEFT_RIGHT_REMAP         0x22
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_COM_PINS_HARDWARE_CONFIGURATION_SETTING_BYTE1_ALTERNATIVE_COM_AND_ENABLE_COM_LEFT_RIGHT_REMAP        0x32

//TIMING & DRIVING SCHEME SETTING COMMAND TABLE

    //SET_DISPLAY_CLOCK_DIVIDE_OSCILLATOR_FREQUENCY
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_DISPLAY_CLOCK_DIVIDE_OSCILLATOR_FREQUENCY_HEAD                               0xD5
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_DISPLAY_CLOCK_DIVIDE_OSCILLATOR_FREQUENCY_SETTING_BYTE1_DIVIDE_RATIO         0b10000000 // divide_ratio = 0b3 ~ 0b0 + 1   Oscillator Frequency = 0xb7 ~ 0xb4 reset 0b10000000

    //SET_PRE_CHARGE_PERIOD
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PRE_CHARGE_PERIOD_HEAD                               0xD9
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_PRE_CHARGE_PERIOD_SETTING_BYTE1_DIVIDE_RATIO         0x22 //  Phase 1 period = 0b3 ~ 0b0 + 1    Phase 2 period = 0xb7 ~ 0xb4 reset 0x22

    //SET_VCOMH_DESELECT_LEVEL
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VCOMH_DESELECT_LEVEL_HEAD                               0xDB
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VCOMH_DESELECT_LEVEL_SETTING_BYTE1_VCOMH_DESELECT_LEVEL1        0x0 // 0xb6 ~ 0xb4 0.65 x VCC
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VCOMH_DESELECT_LEVEL_SETTING_BYTE1_VCOMH_DESELECT_LEVEL2        0x20 // 0xb6 ~ 0xb4 0.77 x VCC reset
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_SET_VCOMH_DESELECT_LEVEL_SETTING_BYTE1_VCOMH_DESELECT_LEVEL3        0x30 // 0xb6 ~ 0xb4 0.83 x VCC

    //NOP
#define SSD1306_OLED_DATA_BYTE_CMD_SINGLE_BYTE_NOP_HEAD                 0xE3

//CHARGE PUMP COMMAND TABLE

    //CHARGE_PUMP_SETTING
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CHARGE_PUMP_SETTING_HEAD                                    0x8D
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CHARGE_PUMP_SETTING_SETTING_BYTE1_DISABLE_CHARGE_PUMP       0x10;
#define SSD1306_OLED_DATA_BYTE_CMD_MULTI_BYTE_CHARGE_PUMP_SETTING_SETTING_BYTE1_ENABLE_CHARGE_PUMP        0x14;




int ssd1306_oled_init(register_ssd1306_oled_parameters *);
int ssd1306_oled_ioctl(ssd1306_oled_ioctl_parameters *);
int ssd1306_oled_deinit(unregister_ssd1306_oled_parameters *);
int ssd1306_oled_deint(i2c_controller_context *, i2c_controller_ioctl_parameters *, uint8_t *);


#endif // __SSD1306_OLED_RASPBERRY_PI_H__



